server/controllers/SiteController.php
<?php

namespace server\controllers;

use ifinance\scoring\interfaces\Logger;
use ifinance\scoring\Version;
use server\models\TestFileModel;
use server\models\TestModel;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\UploadedFile;
use Yii;

/**
 * Class SiteController
 * @package micro\controllers
 */
class SiteController extends Controller
{
    /**
     * @param $action
     * @return bool
     * @throws BadRequestHttpException
     */
    public function beforeAction($action)
    {
        Logger::setLogLevel(100);
        return parent::beforeAction($action);
    }

    /**
     * @return string
     */
    public function actionIndex(): string
    {
        $result = null;
        try {
            $model = new TestModel();
            if (\Yii::$app->request->isPost) {
                $model->load(\Yii::$app->request->post());
                if ($model->validate()) {
                    $runner = Version::current()->run($model->getJson());
                    $result = $runner->getAll();
                }
            }
        } catch (\Throwable $e) {
            $result = [
                'status' => 'error',
                'exception' => [
                    'message' => $e->getMessage(),
                    'file' => $e->getFile(),
                    'line' => $e->getLine(),
                    'trace' => $e->getTraceAsString()
                ]
            ];
        }
        return $this->render('index', ['model' => $model, 'result' => $result]);
    }

    /**
     * @return string|void
     */
    public function actionSaveIndex()
    {
        if (\Yii::$app->request->isPost) {
            $model = new TestModel();
            $model->load(\Yii::$app->request->post());
            if ($model->validate()) {
                return $model->getJson();
            }
        }
    }

    /**
     * @return string
     */
    public function actionTestFile()
    {
        $result = null;
        try {
            $model = new TestFileModel();
            if (\Yii::$app->request->isPost) {
                $post = \Yii::$app->request->post();
//            $post = Json::decode($post);
                $model->configure = UploadedFile::getInstance($model, 'configure');
                if ($model->validate()) {
                    $name = rand() . '.json';
                    if (!$model->configure->saveAs('tmp/' . $name)) {
                        $result = '{status: "error"}';
                    } else {
                        $data = file_get_contents(__DIR__ . '/../web/tmp/' . $name);
                        unlink(__DIR__ . '/../web/tmp/' . $name);
                        $runner = Version::current()->run($data);
                        $result = $runner->getAll();
                    }
                }
            }
        } catch (\Throwable $e) {
            $result = [
                'status' => 'error',
                'exception' => [
                    'message' => $e->getMessage(),
                    'file' => $e->getFile(),
                    'line' => $e->getLine(),
                    'trace' => $e->getTraceAsString()
                ]
            ];
        }
        return $this->render('test-file', ['model' => $model, 'result' => $result]);
    }
}

server/views/site/index.php
<?php

use kdn\yii2\JsonEditor;
use Yii;

/* @var $this \yii\web\View */
/* @var $model \server\models\TestModel */
/* @var $result array|null */

$this->registerJsFile('/js/index.js', ['depends' => [\yii\web\JqueryAsset::className()]]);
?>
<?php if ($result !== null) : ?>
    <div class="panel panel-info">
        <div class="panel-heading">Result</div>
        <div class="panel-body">
            <?= JsonEditor::widget([
                'clientOptions' => ['mode' => 'view'],
                'collapseAll' => ['view'],
                'name' => 'viewer',
                'value' => \yii\helpers\Json::encode($result),
            ]) ?>
        </div>
    </div>
<?php endif; ?>
<?php
$form = \yii\widgets\ActiveForm::begin([
    'id' => 'test-form',
    'options' => ['enctype' => 'multipart/form-data']
]);
?>
<div class="panel panel-primary">
    <div class="panel-heading">Text input</div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-12">
                <?= $form->field($model, 'bkiFile')->widget(
                    JsonEditor::class,
                    [
                        'clientOptions' => ['modes' => ['code', 'tree']],
                    ]
                ); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <?= $form->field($model, 'zone')->widget(
                    JsonEditor::class,
                    [
                        'clientOptions' => ['modes' => ['code', 'tree']],
                    ]
                ); ?>
            </div>
            <div class="col-md-6">
                <?= $form->field($model, 'params')->widget(
                    JsonEditor::class,
                    [
                        'clientOptions' => ['modes' => ['code', 'tree']],
                    ]
                ); ?>
            </div>
            <div class="col-md-12">
                <?= $form->field($model, 'global')->widget(
                    JsonEditor::class,
                    [
                        'clientOptions' => ['modes' => ['code', 'tree']],
                    ]
                ); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-5 col-md-1 col-xs-6">
                <?= \yii\helpers\Html::submitButton('Test', ['class' => 'btn btn-primary']); ?>
            </div>
            <div class="col-md-6 col-xs-6">
                <?= \yii\helpers\Html::a('Save', '#test-form', ['class' => 'btn btn-primary', 'id' => 'save']); ?>
            </div>
        </div>
    </div>
</div>
<?php \yii\widgets\ActiveForm::end(); ?>

<script type="text/javascript">
    var SaveUrl = '<?=\yii\helpers\Url::toRoute(['/site/save-index'])?>';
</script>

server/views/site/one-test.php
<?php

use kdn\yii2\JsonEditor;

/* @var $this \yii\web\View */
/* @var $model \server\models\OneTestModel */
/* @var $result array|null */
?>
<?php if ($result !== null) : ?>
    <div class="panel panel-info">
        <div class="panel-heading">Result</div>
        <div class="panel-body">
            <?= JsonEditor::widget([
                'clientOptions' => ['mode' => 'view'],
                'collapseAll' => ['view'],
                'name' => 'viewer',
                'value' => \yii\helpers\Json::encode($result),
            ]) ?>
        </div>
    </div>
<?php endif; ?>
<?php
$form = \yii\widgets\ActiveForm::begin([
    'id' => 'test-form',
    'options' => ['enctype' => 'multipart/form-data']
]);
?>
    <div class="panel panel-primary">
        <div class="panel-heading">Text input</div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'configure')->widget(
                        JsonEditor::class,
                        [
                            'clientOptions' => ['modes' => ['code', 'tree']],
                        ]
                    ); ?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-lf-offset-1 col-lg-11">
                    <?= \yii\helpers\Html::submitButton('Test', ['class' => 'btn btn-primary']); ?>
                </div>
            </div>
        </div>
    </div>
<?php \yii\widgets\ActiveForm::end(); ?>

server/views/site/test-file.php
<?php

use kdn\yii2\JsonEditor;

/* @var $this \yii\web\View */
/* @var $model \server\models\TestFileModel */
/* @var $result array|null */
?>
<?php if ($result !== null) : ?>
    <div class="panel panel-info">
        <div class="panel-heading">Result</div>
        <div class="panel-body">
            <?= JsonEditor::widget([
                'clientOptions' => ['mode' => 'view'],
                'collapseAll' => ['view'],
                'name' => 'viewer',
                'value' => \yii\helpers\Json::encode($result),
            ]) ?>
        </div>
    </div>
<?php endif; ?>
<?php
$form = \yii\widgets\ActiveForm::begin([
    'id' => 'test-form',
    'options' => ['enctype' => 'multipart/form-data']
]);
?>
    <div class="panel panel-primary">
        <div class="panel-heading">Text input</div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    <?= $form->field($model, 'configure')->fileInput(); ?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-lf-offset-1 col-lg-11">
                    <?= \yii\helpers\Html::submitButton('Test', ['class' => 'btn btn-primary']); ?>
                </div>
            </div>
        </div>
    </div>
<?php \yii\widgets\ActiveForm::end(); ?>