server/controllers/CreateGlobalParamsController.php
<?php

namespace server\controllers;

use server\models\CreateNewGlobalParamsModel;
use server\models\CreateOldGlobalParamsModel;
use yii\helpers\Json;
use yii\web\Controller;
use Yii;

/**
 * Class CreateGlobalParamsController
 * @package server\controllers
 */
class CreateGlobalParamsController extends Controller
{
    /**
     * @return string|void
     * @throws \yii\web\RangeNotSatisfiableHttpException
     */
    public function actionNew()
    {
        $model = new CreateNewGlobalParamsModel();

        if (Yii::$app->request->isPost) {
            $model->load(Yii::$app->request->post());
            if ($model->validate()) {
                Yii::$app->response->sendContentAsFile(Json::encode($model->attributes), 'global_new.json');
                return;
            }
        }

        return $this->render('new', ['model' => $model]);
    }

    /**
     * @return string|void
     * @throws \yii\web\RangeNotSatisfiableHttpException
     */
    public function actionOld()
    {
        $model = new CreateOldGlobalParamsModel();

        if (Yii::$app->request->isPost) {
            $model->load(Yii::$app->request->post());
            if ($model->validate()) {
                Yii::$app->response->sendContentAsFile(Json::encode($model->attributes), 'global_old.json');
                return;
            }
        }

        return $this->render('old', ['model' => $model]);
    }
}

server/controllers/CreateParamsController.php
<?php

namespace server\controllers;

use server\models\CreateNewParamsModel;
use server\models\CreateOldParamsModel;
use yii\web\Controller;
use Yii;
use yii\web\RangeNotSatisfiableHttpException;

/**
 * Class CreateParamsController
 * @package server\controllers
 */
class CreateParamsController extends Controller
{
    /**
     * @return string|void
     * @throws RangeNotSatisfiableHttpException
     */
    public function actionNew()
    {
        $model = new CreateNewParamsModel();
        if (Yii::$app->request->isPost) {
            $model->load(Yii::$app->request->post());
            if ($model->validate()) {
                Yii::$app->response->sendContentAsFile($model->getJson(), 'generate_new.json');
                return;
            }
        }
        return $this->render('new', ['model' => $model]);
    }

    /**
     * @return string|void
     * @throws RangeNotSatisfiableHttpException
     */
    public function actionOld()
    {
        $model = new CreateOldParamsModel();
        if (Yii::$app->request->isPost) {
            $model->load(Yii::$app->request->post());
            if ($model->validate()) {
                Yii::$app->response->sendContentAsFile($model->getJson(), 'generate_old.json');
                return;
            }
        }
        return $this->render('old', ['model' => $model]);
    }
}

server/controllers/SiteController.php
<?php

namespace server\controllers;

use ifinance\scoring\interfaces\Logger;
use ifinance\scoring\Version;
use server\models\TestFileModel;
use server\models\TestModel;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\UploadedFile;
use Yii;

/**
 * Class SiteController
 * @package micro\controllers
 */
class SiteController extends Controller
{
    /**
     * @param $action
     * @return bool
     * @throws BadRequestHttpException
     */
    public function beforeAction($action)
    {
        Logger::setLogLevel(100);
        return parent::beforeAction($action);
    }

    /**
     * @return string
     */
    public function actionIndex(): string
    {
        $result = null;
        try {
            $model = new TestModel();
            if (\Yii::$app->request->isPost) {
                $model->load(\Yii::$app->request->post());
                if ($model->validate()) {
                    $runner = Version::current()->run($model->getJson());
                    $result = $runner->getAll();
                }
            }
        } catch (\Throwable $e) {
            $result = [
                'status' => 'error',
                'exception' => [
                    'message' => $e->getMessage(),
                    'file' => $e->getFile(),
                    'line' => $e->getLine(),
                    'trace' => $e->getTraceAsString()
                ]
            ];
        }
        return $this->render('index', ['model' => $model, 'result' => $result]);
    }

    /**
     * @return string|void
     */
    public function actionSaveIndex()
    {
        if (\Yii::$app->request->isPost) {
            $model = new TestModel();
            $model->load(\Yii::$app->request->post());
            if ($model->validate()) {
                return $model->getJson();
            }
        }
    }

    /**
     * @return string
     */
    public function actionTestFile()
    {
        $result = null;
        try {
            $model = new TestFileModel();
            if (\Yii::$app->request->isPost) {
                $post = \Yii::$app->request->post();
//            $post = Json::decode($post);
                $model->configure = UploadedFile::getInstance($model, 'configure');
                if ($model->validate()) {
                    $name = rand() . '.json';
                    if (!$model->configure->saveAs('tmp/' . $name)) {
                        $result = '{status: "error"}';
                    } else {
                        $data = file_get_contents(__DIR__ . '/../web/tmp/' . $name);
                        unlink(__DIR__ . '/../web/tmp/' . $name);
                        $runner = Version::current()->run($data);
                        $result = $runner->getAll();
                    }
                }
            }
        } catch (\Throwable $e) {
            $result = [
                'status' => 'error',
                'exception' => [
                    'message' => $e->getMessage(),
                    'file' => $e->getFile(),
                    'line' => $e->getLine(),
                    'trace' => $e->getTraceAsString()
                ]
            ];
        }
        return $this->render('test-file', ['model' => $model, 'result' => $result]);
    }
}

server/views/layouts/main.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */

\yii\web\YiiAsset::register($this);
\yii\web\JqueryAsset::register($this);
\yii\bootstrap\BootstrapAsset::register($this);

use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\helpers\Html;
use yii\helpers\Json;

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>

<body><?php $this->beginBody() ?>
<?php
NavBar::begin(['brandLabel' => 'Scoring', 'options' => ['class' => 'navbar-inverse']]);
echo Nav::widget([
    'items' => [
        ['label' => 'Test', 'url' => ['/site/index']],
        ['label' => 'Test File', 'url' => ['/site/test-file']],
        ['label' => 'Create params', 'items' => [
            ['label' => 'new', 'url' => ['/create-params/new']],
            ['label' => 'old', 'url' => ['/create-params/old']]
        ]],
        ['label' => 'Create global params', 'items' => [
            ['label' => 'new', 'url' => ['/create-global-params/new']],
            ['label' => 'old', 'url' => ['/create-global-params/old']]
        ]],
    ],
    'options' => ['class' => 'navbar-nav'],
]);
NavBar::end();
?>
<div class="container">
    <?= $content ?>
</div>
<div class="container">
    <div class="panel panel-primary">
        <div class="panel-heading">Logger</div>
        <div class="panel-body">
            <?php foreach (\ifinance\scoring\interfaces\Logger::get() as $class => $items) : ?>
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th><?= $class; ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($items as $id => $item) : ?>
                            <?php if (is_array($item)) :
                                foreach ($item as &$val) {
                                    $val = Json::decode($val);
                                }
                                ?>
                                <tr class="warning">
                                    <td><?= $id; ?></td>
                                    <td><?= \kdn\yii2\JsonEditor::widget([
                                            'clientOptions' => ['modes' => ['code', 'tree']],
                                            'name' => rand(),
                                            'value' => Json::encode($item)
                                        ]) ?></td>
                                </tr>
                            <?php else : ?>
                                <tr class="warning">
                                    <td><?= $id; ?></td>
                                    <td><?= $item; ?></td>
                                </tr>
                            <?php endif; ?>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>